---

version: "3.3"

services:

  app:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: "mohamedlavu/docker-nginx:latest"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: "mohamedlavu/docker-php8:latest"
    container_name: php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: mohamedlavu/docker-node-latest:latest
    container_name: node
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
      - appnet

  db:
    image: mysql:latest
    container_name: db
    #restart: unless-stopped
    #tty: true
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql:/var/lib/mysql-files
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "9090:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis

networks:
  appnet:
    driver: "bridge"

#Volumes
volumes:
  dbdata:
    driver: local
